version: '3'

networks:
    rede-siga:
        driver: bridge

services:

    siga-service:
        depends_on:
            - siga-mysql
        build:
            args:
                user: siga
                uid: 1000
            context: ./
            dockerfile: ./docker/service.dockerfile
        image: spu/siga-service
        container_name: siga-service
        restart: unless-stopped
        working_dir: /var/www
        volumes: 
            - "./:/var/www"
        networks:
            - rede-siga

    siga-mysql:
        image: mysql:5.7
        container_name: siga-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        # Permite a escrita em volumes no Windows 10
        command:
            'mysqld --innodb-flush-method=fsync'
        ports: 
            - "3306:3306"
        #volumes:
        #    - ./docker/mysql/basezero:/docker-entrypoint-initdb.d
        networks:
            - rede-siga

    siga-nginx: 
        depends_on:
            - siga-service
        image: nginx:alpine
        container_name: siga-nginx
        restart: unless-stopped
        ports: 
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks: 
            - rede-siga

    siga-phpmyadmin:
        depends_on: 
            - siga-mysql
        image: phpmyadmin/phpmyadmin
        container_name: siga-phpmyadmin
        environment: 
            PMA_HOST: siga-mysql
            PMA_PORT: 3306
        restart: always
        ports:
            - 8080:80
        networks: 
            - rede-siga